/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame_MODELOS;

import JFrame_TecnoAr.Main;
import Conexao.Conexao;
import Log.arquivoLog;
import Tabelas_MODELOS.JTableCadastroMilitar;
import Uteis.Data;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Guedes
 */
public class jfCadastroMilitares extends javax.swing.JFrame {

    /**
     * Creates new form Militar
     */
    Conexao conexao = new Conexao();
    Main app;
    public jfCadastroMilitares(Conexao con,Main ap) 
    {
        this.conexao = con;
        this.app = ap;
        initComponents();
        limparCamposCadastroMilitar();
        jsListarMilitar.setViewportView(new JTableCadastroMilitar(conexao,this).getTabela());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCadastrarMilitar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtMilitarNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcMilitarGraduacao = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jtMilitarMatricula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcMilitarQuadro = new javax.swing.JComboBox();
        jsListarMilitar = new javax.swing.JScrollPane();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        jpMilitarSenha = new javax.swing.JPasswordField();
        jLabel59 = new javax.swing.JLabel();
        jtMilitarGuerra = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jrcomum = new javax.swing.JCheckBox();
        jrchefedoscov = new javax.swing.JCheckBox();
        jradjunto = new javax.swing.JCheckBox();
        jrsupervisorcov = new javax.swing.JCheckBox();
        jrsupervisoradjunto = new javax.swing.JCheckBox();
        jrsecaomaterial = new javax.swing.JCheckBox();
        jrestatistica = new javax.swing.JCheckBox();
        jrdarthvader = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Militares");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Graduação");

        jtMilitarNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtMilitarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMilitarNomeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nome Completo");

        jcMilitarGraduacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcMilitarGraduacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Soldado", "Cabo", "3º Sargento", "2º Sargento", "1º Sargento", "Subtenente", "Aspirante a Oficial", "2º Tenente", "1º Tenente", "Capitão", "Major", "Ten. Coronel", "Coronel" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Matrícula");

        jtMilitarMatricula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtMilitarMatricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtMilitarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMilitarMatriculaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Quadro");

        jcMilitarQuadro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcMilitarQuadro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Combatente", "Condutor", "Administrativo" }));

        jToolBar1.setFloatable(false);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cad_ico.png"))); // NOI18N
        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancel.png"))); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jLabel58.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel58.setText("Senha");

        jpMilitarSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jpMilitarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpMilitarSenhaActionPerformed(evt);
            }
        });

        jLabel59.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel59.setText("Nome Guerra");

        jtMilitarGuerra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtMilitarGuerra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMilitarGuerraActionPerformed(evt);
            }
        });

        jLabel60.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("Permissão");

        jrcomum.setText("Comum");

        jrchefedoscov.setText("Chefe dos COV");

        jradjunto.setText("Adjunto");

        jrsupervisorcov.setText("Supervisor COV");

        jrsupervisoradjunto.setText("Supervisor Adjunto");

        jrsecaomaterial.setText("Seção de Material");

        jrestatistica.setText("Estatistica");

        jrdarthvader.setText("Darth Vader");

        javax.swing.GroupLayout jpCadastrarMilitarLayout = new javax.swing.GroupLayout(jpCadastrarMilitar);
        jpCadastrarMilitar.setLayout(jpCadastrarMilitarLayout);
        jpCadastrarMilitarLayout.setHorizontalGroup(
            jpCadastrarMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastrarMilitarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadastrarMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsListarMilitar)
                    .addGroup(jpCadastrarMilitarLayout.createSequentialGroup()
                        .addGroup(jpCadastrarMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCadastrarMilitarLayout.createSequentialGroup()
                                .addGroup(jpCadastrarMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jtMilitarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpCadastrarMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jcMilitarGraduacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpCadastrarMilitarLayout.createSequentialGroup()
                                .addGroup(jpCadastrarMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jcMilitarQuadro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpCadastrarMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel58)
                                    .addComponent(jpMilitarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpCadastrarMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtMilitarGuerra, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel59))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jpCadastrarMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtMilitarMatricula)
                            .addGroup(jpCadastrarMilitarLayout.createSequentialGroup()
                                .addGroup(jpCadastrarMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 20, Short.MAX_VALUE))))
                    .addGroup(jpCadastrarMilitarLayout.createSequentialGroup()
                        .addGroup(jpCadastrarMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpCadastrarMilitarLayout.createSequentialGroup()
                                .addComponent(jrcomum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrchefedoscov)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jradjunto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrsupervisorcov)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrsupervisoradjunto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrsecaomaterial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrestatistica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrdarthvader)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpCadastrarMilitarLayout.setVerticalGroup(
            jpCadastrarMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastrarMilitarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadastrarMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastrarMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtMilitarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcMilitarGraduacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtMilitarMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCadastrarMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCadastrarMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jpCadastrarMilitarLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jcMilitarQuadro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCadastrarMilitarLayout.createSequentialGroup()
                        .addGroup(jpCadastrarMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel58)
                            .addComponent(jLabel59))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpCadastrarMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jpMilitarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtMilitarGuerra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel60)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCadastrarMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrcomum)
                    .addComponent(jrchefedoscov)
                    .addComponent(jradjunto)
                    .addComponent(jrsupervisorcov)
                    .addComponent(jrsupervisoradjunto)
                    .addComponent(jrsecaomaterial)
                    .addComponent(jrestatistica)
                    .addComponent(jrdarthvader))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jsListarMilitar, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 821, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 15, Short.MAX_VALUE)
                    .addComponent(jpCadastrarMilitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 16, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpCadastrarMilitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtMilitarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMilitarNomeActionPerformed
        jtMilitarNome.setText(jtMilitarNome.getText().toUpperCase());
        jtMilitarMatricula.requestFocus(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMilitarNomeActionPerformed

    private void jtMilitarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMilitarMatriculaActionPerformed
        jpMilitarSenha.requestFocus(true);
    }//GEN-LAST:event_jtMilitarMatriculaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Deseja SALVAR?","SALVAR REGISTRO",JOptionPane.YES_NO_OPTION)==0)
        {
            if(verificaMilitar())
            salvarMilitar();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Deseja limpar os campos?","Limpar Campos",JOptionPane.YES_NO_OPTION)==0)
        {
            limparCamposCadastroMilitar();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jpMilitarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpMilitarSenhaActionPerformed
        jtMilitarGuerra.requestFocus(true);
    }//GEN-LAST:event_jpMilitarSenhaActionPerformed

    private void jtMilitarGuerraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMilitarGuerraActionPerformed
        jtMilitarGuerra.setText(jtMilitarGuerra.getText().toUpperCase());        // TODO add your handling code here:
    }//GEN-LAST:event_jtMilitarGuerraActionPerformed
/**
   * Alterar militar cadastrado
   * @param nome
   * @param matricula
   * @param senha
   * @param graduacao
   * @param nome_guerra
   * @param quadro 
   */
public void alterarMilitar(String nome,String matricula,String senha,String graduacao,String nome_guerra, String quadro,
        String comum,String chefe_dos_cov,String adjunto,String supervisor_cov,String supervisor_adjunto,
        String secao_material,String estatistica, String darth_vader)
{
    jtMilitarNome.setText(nome);
    jtMilitarMatricula.setText(matricula);
    jtMilitarGuerra.setText(nome_guerra);
    jcMilitarQuadro.setSelectedItem(quadro);
    jcMilitarGraduacao.setSelectedItem(graduacao);
    jpMilitarSenha.setText(senha);
    jrcomum.setSelected(new Boolean(comum));
    jrchefedoscov.setSelected(new Boolean(chefe_dos_cov));
    jradjunto.setSelected(new Boolean(adjunto));
    jrsupervisorcov.setSelected(new Boolean(supervisor_cov));
    jrsupervisoradjunto.setSelected(new Boolean(supervisor_adjunto));
    jrsecaomaterial.setSelected(new Boolean(secao_material));
    jrestatistica.setSelected(new Boolean(estatistica));
    jrdarthvader.setSelected(new Boolean(darth_vader));
}
    private void salvarMilitar() 
    {
        System.out.println("salvar militar");
        String nome = jtMilitarNome.getText().toUpperCase();
        String matricula = jtMilitarMatricula.getText();
        String graduacao = jcMilitarGraduacao.getSelectedItem().toString();
        String quadro = jcMilitarQuadro.getSelectedItem().toString();
        String senha = jpMilitarSenha.getText();
        String nome_guerra = jtMilitarGuerra.getText().toUpperCase();
        String comum = jrcomum.isSelected()+"";
        String chefe_dos_cov = jrchefedoscov.isSelected()+"";
        String adjunto = jradjunto.isSelected()+"";
        String supervisor_cov = jrsupervisorcov.isSelected()+"";
        String supervisor_adjunto = jrsupervisoradjunto.isSelected()+"";
        String secao_material = jrsecaomaterial.isSelected()+"";
        String estatistica = jrestatistica.isSelected()+"";
        String darth_vader = jrdarthvader.isSelected()+"";
        try
        {
            conexao.executeSQL("SELECT * FROM bombeiro_19.militar ORDER BY nome ASC");
            conexao.resultset.first();
            int compare = 0;
            int idd=0;
            do
            {
                if(nome.compareToIgnoreCase(conexao.resultset.getString("nome"))==0)
                        {
                            idd = conexao.resultset.getInt("id_militar");
                            compare = 1;
                            break;
                        }
                
            }while(conexao.resultset.next());
            System.out.println(compare);
            if(compare==0)
            {
                String sqlInsert = "INSERT INTO bombeiro_19.militar "
                    + "(nome,matricula,graduacao,senha,nome_guerra,quadro,comum,chefe_dos_cov,adjunto,supervisor_cov,supervisor_adjunto,secao_material,estatistica,darth_vader) VALUES "
                    + "('"+nome+"','"+matricula+"','"+graduacao+"','"+senha+"','"+nome_guerra+"','"+quadro+"','"+comum+"','"+chefe_dos_cov+"','"+adjunto+"','"+supervisor_cov+"','"+supervisor_adjunto+"','"+secao_material+"','"+estatistica+"','"+darth_vader+"')";
                conexao.statement.executeUpdate(sqlInsert);
            }
            else
            {
                String sqlUpdate = "UPDATE bombeiro_19.militar SET "
                        + "nome='"+nome+"', "
                        + "matricula='"+matricula+"', "
                        + "graduacao='"+graduacao+"', "
                        + "senha='"+senha+"',"
                        + "nome_guerra='"+nome_guerra+"', "
                        + "quadro='"+quadro+"',"
                        + "comum='"+comum+"', "
                        + "chefe_dos_cov = '"+chefe_dos_cov+"',"
                        + "adjunto = '"+adjunto+"',"
                        + "supervisor_cov = '"+supervisor_cov+"',"
                        + "supervisor_adjunto = '"+supervisor_adjunto+"',"
                        + "secao_material = '"+secao_material+"',"
                        + "estatistica = '"+estatistica+"',"
                        + "darth_vader = '"+darth_vader+"' "
               + "WHERE  id_militar = "+idd;
                System.out.println(sqlUpdate);
       conexao.executeSQL("select * from bombeiro_19.militar ORDER BY nome ASC limit 10");
            conexao.statement.executeUpdate(sqlUpdate);
            }
            limparCamposCadastroMilitar();
        }
        catch(SQLException er)
        {
            String log = "|"+new Data().getDataF()+" ás "+new Data().getHora()+"|  SQLException: "+er.getMessage();
            new arquivoLog(log);
        }
        catch(NumberFormatException nfe)
        {
            String log = "|"+new Data().getDataF()+" ás "+new Data().getHora()+"|  NumberFormatException: "+nfe.getMessage();
            new arquivoLog(log);
        }
         catch(Exception ex)
        {
            String log = "|"+new Data().getDataF()+" ás "+new Data().getHora()+"|  Exception: "+ex.getMessage();
            new arquivoLog(log);
        }
    }
    private boolean verificaMilitar() 
    {
        if(jtMilitarNome.getText().length()<3)
        {
            jtMilitarNome.requestFocus(true);
            return false;
        }
        if(jtMilitarMatricula.getText().length()<2)
        {
            jtMilitarMatricula.requestFocus(true);
            return false;
        }
        if(jtMilitarGuerra.getText().length()<2)
        {
            jtMilitarGuerra.requestFocus(true);
            return false;
        }
        return true;
    }
    public void limparCamposCadastroMilitar() 
    {
        jtMilitarGuerra.setText("");
        jtMilitarMatricula.setText("");
        jtMilitarNome.setText("");
        jcMilitarGraduacao.setSelectedIndex(0);
        jcMilitarQuadro.setSelectedIndex(0);
        jpMilitarSenha.setText("");
        jsListarMilitar.setViewportView(new JTableCadastroMilitar(conexao,this).getTabela());
        jrcomum.setSelected(true);
        jrchefedoscov.setSelected(false);
        jradjunto.setSelected(false);
        jrsupervisorcov.setSelected(false);
        jrsupervisoradjunto.setSelected(false);
        jrsecaomaterial.setSelected(false);
        jrestatistica.setSelected(false);
        jrdarthvader.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox jcMilitarGraduacao;
    private javax.swing.JComboBox jcMilitarQuadro;
    private javax.swing.JPanel jpCadastrarMilitar;
    private javax.swing.JPasswordField jpMilitarSenha;
    private javax.swing.JCheckBox jradjunto;
    private javax.swing.JCheckBox jrchefedoscov;
    private javax.swing.JCheckBox jrcomum;
    private javax.swing.JCheckBox jrdarthvader;
    private javax.swing.JCheckBox jrestatistica;
    private javax.swing.JCheckBox jrsecaomaterial;
    private javax.swing.JCheckBox jrsupervisoradjunto;
    private javax.swing.JCheckBox jrsupervisorcov;
    private javax.swing.JScrollPane jsListarMilitar;
    private javax.swing.JTextField jtMilitarGuerra;
    private javax.swing.JTextField jtMilitarMatricula;
    private javax.swing.JTextField jtMilitarNome;
    // End of variables declaration//GEN-END:variables
}
